In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Exercise 1: Vectorized Operations: Writing Optimized Code

1. Generate a 1000 × 1000 matrix of random integers between 0 (included) and 20 (excluded).
2. Compute the sum of diagonal elements using a for loop.
3. Compute the sum of diagonal elements using a NumPy linear algebra function.
4. Compare the running times of 2. and 3. with %%timeit (the %% syntax allows timing multiple lines).
Hint: use numpy.random.randint.

In [24]:
matrix = np.random.randint(0, 20, size=(1000, 1000))

In [25]:
%%timeit
sum = 0
for i in np.arange(1000):
    sum += matrix[i, i]

127 µs ± 1.5 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [26]:
%%timeit
trace = np.trace(matrix)

1.34 µs ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Exercise 2: Fibonacci Numbers with Binet Formula

1. Using NumPy, compute the first 20 numbers of the Fibonacci series Fn (n = 1, 2, . . . , 10) with Binet formula

In [27]:
def binet_formula(n):
    return (np.power(1+np.sqrt(5), n) - np.power(1-np.sqrt(5), n))/(2**n*np.sqrt(5))

first_twenty = binet_formula(np.arange(20)+1)
print(first_twenty)

[1.000e+00 1.000e+00 2.000e+00 3.000e+00 5.000e+00 8.000e+00 1.300e+01
 2.100e+01 3.400e+01 5.500e+01 8.900e+01 1.440e+02 2.330e+02 3.770e+02
 6.100e+02 9.870e+02 1.597e+03 2.584e+03 4.181e+03 6.765e+03]


# Exercise 3: Quantum Harmonic Oscillator

In this exercise, you will find the bound states of the 1d quantum harmonic oscillator of mass m by solving the time-independent Schr ̈odinger equation numerically. This equation is an eigenvalue problem
Hψn = Enψn
where H = K + V = − h ̄2 ∂2 + 1 mω2x2 is the Hamiltonian operator, ψ is the wavefunction (eigenfunction),
2m x 2 n and En the energy level (eigenvalue). In the following, set h ̄ = m = ω = 1.
1. Space discretization. Consider the interval [−10, 10] and discretize it generating a mesh of uniform spacing ∆x = 0.01 with N points, i.e., xi = −10 + i∆x (i = 0,1,...,N − 1). In this space, the wavefunction ψ is a vector with components (ψ)i = ψ(xi).
2. Hamiltonian discretization. Using this discretization, the Hamiltonian becomes a N × N matrix. In particular, the kinetic energy term is

()

where we used the finite-difference approximation of the second derivative, and the potential energy
term is

()

Generate the Hamiltonian matrix Hˆ = Kˆ + Vˆ .

3. Diagonalization. Diagonalize Hˆ using numpy.linalg.eig and numpy.linalg.eigh, which is specific for symmetric matrices. Use %%timeit to compare running times. Check that the eigenvalues are sorted in increasing order, and if not, do so.
4. Normalize the wavefunctions (eigenfunctions) of Hˆ computing the normalization constant
Z =
sZ 10 vuN−1
ψ∗(x)ψ(x)dx ≈ ut X ψ∗(xi)ψ(xi)∆x.
−10
i=0
5. Plot the first 10 (normalized) wavefunctions and print the values of the corresponding energy levels (eigenvalues1 ). Compare with the theoretical predictions En = (n + 21 ).
Hint: use numpy.arange, numpy.diag, numpy.argsort, matplotlib.pyplot.plot.


In [11]:
delta_x = 0.01
size = int(20/delta_x) + 1
x_space, step = np.linspace(-10, 10, num=int(20/delta_x)+1, retstep = True)
print(step)
print(x_space)

0.01
[-10.    -9.99  -9.98 ...   9.98   9.99  10.  ]


In [26]:
K = -1/(2*delta_x**2)*(np.diag(-2*np.ones(size))+np.diag(1*np.ones(size-1), k=1)+np.diag(1*np.ones(size-1), k=-1))
print(K)

def V_calc(x):
    return 1/2*x**2

V_vec = V_calc(x_space)
V = 1/2*np.diag(V_vec)
print(V)

H = K + V
print(H)

[[10000. -5000.    -0. ...    -0.    -0.    -0.]
 [-5000. 10000. -5000. ...    -0.    -0.    -0.]
 [   -0. -5000. 10000. ...    -0.    -0.    -0.]
 ...
 [   -0.    -0.    -0. ... 10000. -5000.    -0.]
 [   -0.    -0.    -0. ... -5000. 10000. -5000.]
 [   -0.    -0.    -0. ...    -0. -5000. 10000.]]
[[25.        0.        0.       ...  0.        0.        0.      ]
 [ 0.       24.950025  0.       ...  0.        0.        0.      ]
 [ 0.        0.       24.9001   ...  0.        0.        0.      ]
 ...
 [ 0.        0.        0.       ... 24.9001    0.        0.      ]
 [ 0.        0.        0.       ...  0.       24.950025  0.      ]
 [ 0.        0.        0.       ...  0.        0.       25.      ]]
[[10025.       -5000.           0.       ...     0.           0.
      0.      ]
 [-5000.       10024.950025 -5000.       ...     0.           0.
      0.      ]
 [    0.       -5000.       10024.9001   ...     0.           0.
      0.      ]
 ...
 [    0.           0.           0.       ...

In [27]:
eigenvalues, eigenvectors = np.linalg.eig(H)
print(eigenvalues)

[20019.78223004 20016.06330319 20013.17378806 ...   768.07170486
  1032.99425517   444.97692994]


In [59]:
eigenvalues, eigenvectors = np.linalg.eigh(H)
print(eigenvalues)

[3.53551828e-01 1.06065236e+00 1.76774664e+00 ... 2.00160633e+04
 2.00197822e+04 2.00197822e+04]


In [63]:
# Normalize

def normalize(eigenvectors):
    return np.sqrt(np.sum(np.square(eigenvectors), axis = 0)*delta_x)

print(eigenvectors.shape)
Z = (normalize(eigenvectors)[np.newaxis]).T

(2001, 2001)


In [76]:
## Plot first ten eigenvectors
eigenvec = np.divide(eigenvectors[:, 0:9],Z)
print(np.sum(np.square(eigenvec[:, 6])))
eigenval = eigenvalues[0:9].T[np.newaxis]
print(eigenval.shape)
eigenval = np.divide(eigenval, Z)

100.00000000000004
(1, 9)


In [74]:
print(eigenvec.shape)
print(eigenval.shape)

(2001, 9)
(2001, 9)


In [71]:
for idx, vec in enumerate(eigenvec.T):
    plt.plot(x_space, vec, label = 'Energy = ' + "{:.4f}".format(eigenval[idx]))
    plt.xlabel('x')
    plt.ylabel('psi(x)')
    plt.legend()
    plt.title('eigenvectors SHO')
    plt.show()



SyntaxError: invalid decimal literal (3128753363.py, line 2)